# Generated by Django 5.1.3 on 2024-12-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemphoto',
            old_name='product',
            new_name='item',
        ),
    ]
