# Generated by Django 5.1.3 on 2024-12-14 04:18

import MarketplacePy.common.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[MarketplacePy.common.validators.FileSizeValidator(5), MarketplacePy.common.validators.validate_image_content], verbose_name='photo'),
        ),
    ]
