# Generated by Django 5.1.3 on 2024-12-15 02:36

import MarketplacePy.common.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_itemphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[MarketplacePy.common.validators.FileSizeValidator(5), MarketplacePy.common.validators.validate_image_content], verbose_name='category_image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='main_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[MarketplacePy.common.validators.FileSizeValidator(5), MarketplacePy.common.validators.validate_image_content], verbose_name='item_main_photo'),
        ),
    ]
