# Generated by Django 5.1.3 on 2024-12-06 03:46

import MarketplacePy.accounts.validators
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, validators=[MarketplacePy.accounts.validators.FirstCapitalValidator()])),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, validators=[MarketplacePy.accounts.validators.FirstCapitalValidator()])),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile picture')),
            ],
        ),
    ]
