# Generated by Django 5.1.3 on 2024-12-18 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together={('reviewer', 'reviewed_user')},
        ),
    ]
